### ISSUE TITLE
Applications Process OL doppelte

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-jobs#101]
Im HTML von BITE Stellen ist die ordered List der Darstellung des Application Prozess doppelt:

<img width="1803" alt="grafik" src="https://github.com/user-attachments/assets/28295af4-216a-48d1-a452-98a73072c775">

**Comment by cassandre** [comment]
Kommt aus fau-jobportal, verschiebe ich mal dahin: https://gitlab.rrze.fau.de/rrze-webteam/fau-jobportal/-/issues/34
