### ISSUE TITLE
Filterung von Joblisten nach Keywords

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-jobs#23]
Wunsch von Cathrin: Nutzung der Keywords (in BITE eingebbar) um Joblisten zu filtern

**Comment by xwolfde** [comment]
Aktuell haben wir jetzt den Filter nach category.
Der funktioniert auch über UnivIS-Jobs.

Also [rrze-jobs ... category="" .. ]

mit category einen Wert aus
n-wiss, wiss, azubi, hiwi, prof, other

Achtung: prof gibt es derzeit noch nicht bei der FAU, sondern nur bei der UTN aus deren BITE.

**Comment by lukasniebler** [comment]
Ist dokumentiert und in der Liste der Attribute mit aufgenommen.
