### ISSUE TITLE
Sortierung

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-jobs#24]
Durch den Update funktioniert die Sortierung der Jobs in Listen aktuell nicht mehr korrekt. Diese bitte nochmal angehen.

**Comment by xwolfde** [comment]
Parameter waren:
 'limit',   'orderby',  'order',

**Comment by thenickless** [comment]
Parameter orderby und order:
- [ ] Sortierung nach Titel
- [ ] Sortierung nach Datumsfelder (berücksichtigt "As soon as possible" und dergleichen)
- [ ] Abwärtskompatibel:
Die sortierbaren Felder (Doku vs Output => beide Varianten sind nun möglich)  job_title (title), application_end (validThrough), job_start (jobStartDateSort)
