### ISSUE TITLE
Multisite-Setting für API-Keys

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-jobs#28]
Da wir den API Key von BITE (aber auch später anderer Provider) nicht bei jeder Instanz manuell eingeben können und den dortigen Webmastern sichtbar machen können, sollte es in dem CMS-Settings ein Eintrag für den/die API-Keys geben können (Globale Konstanten o.ä.).

Wenn nun das Plugin auf einer Multisite-Instanz zum EInsatz kommt, soll geschuat werden, ob ein entsprechender API Key vorliegt und dieser dann optional verwendet werden können, ohne dass man den dann noch sehen oder eingeben können.

**Comment by thenickless** [comment]
für rrze-lectures (rrze-campo) nutze ich das (die section heisst dort "basic")
Im Plugin RRZE-Settings gibt es den DIP_apiKey - hier bräuchte man noch einen BITE-Key o.ä:

```
private function getKey()
    {
        $DIPOptions = get_option('rrze-campo');

        if (!empty($DIPOptions['basic_ApiKey'])) {
            return $DIPOptions['basic_ApiKey'];
        }
        elseif (is_multisite()) {
            $settingsOptions = get_site_option('rrze_settings');
            if (!empty($settingsOptions->plugins->DIP_apiKey)) {
                return $settingsOptions->plugins->DIP_apiKey;
            }
        }
        else {
            return '';
        }
    }
```

**Comment by xwolfde** [comment]
im dev
