### ISSUE TITLE
2-Sprachigkeit

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-jobs#34]
- Im Reiter mit den Beschriftungen jeweils 2. Feld für Englisch (defaults könnten wir vorgeben)
- Ausgabe Steuerung nach "lang" der API-Ausgaben

Damit könnte FAU-Jobportal auch wieder zweisprachig werden (war es in V2, aktuell ist V3).

**Comment by xwolfde** [comment]
Also ein Attribut geben wie
  [rrze-jobs ... lang="en" ...]

Dann wird die Ausgabe im englischne erfolgen, sofern das Englische vorhanden ist.
Der Sprachschalter ist aber nicht Sache des Plugins...
