### ISSUE TITLE
Filterung nach Berufsgruppe im Shortcode [jobs]

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-jobs#47]
Das wäre über occupationalCategory möglich (Werte: wiss, n-wiss (oder nwiss => zu überprüfen), tech, azubi, hiwi)

Kundenwunsch: https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=1061448

**Comment by thenickless** [comment]
Info:

für UnivIS gibt es bereits eine Methode get_group()

Sie wird für FAU-Jobportal benötigt und fetched nur Jobs einer bestimmten occupationalCategory.

**Comment by xwolfde** [comment]
Im Shortcode gibt es ein neues Attribut category="".

Diese kann ein Wert aus [wiss, n-wiss, azubi, hiwi, prof, other] übergeben bekommen.

Danach werden die Jobs danach gefiltert.
