### ISSUE TITLE
Fehlerhafte Angabe des Entgelts - TVLE statt A

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-jobs#70]
In https://github.com/RRZE-Webteam/rrze-jobs/blob/main/includes/Provider.php#L542
ist offenbar die Zählung des Arrays falsch
  if (isset($output_array[2])) { ..

Hier und weiter unten muss natürlich bei 0 angefangen werden zu zählen:
Daher $output_array[2]  zu $output_array[1]

Also
```
if (isset($output_array[1])) {
                    $gruppe = $output_array[1];
                    $gruppe = preg_replace('/^0/', '', $gruppe);

                    if ($output_array[0] == "A") {
                        $res = 'A ' . $gruppe . ' BayBesO';
                    } else {
                        $res = 'TV-L E ' . $gruppe;
                    }
                }

```

**Comment by thenickless** [comment]
Die Zählung des Arrays ist korrekt.

### Grund: 

$output_array wird gesetzt mit 

`preg_match('/^([a-z\-\s]*)\s*([0-9ab]+)$/i', $entgeld, $output_array)
`

$output_array entspricht $matches

"(..) **$matches[0] will contain the text that matched the full pattern**, $matches[1] will have the text that matched the first captured parenthesized subpattern, and so on."

Siehe https://www.php.net/manual/en/function.preg-match.php


Bsp:

$output_array ist

```
array(3) {
  [0]=>
  string(8) "TV-L E9b"
  [1]=>
  string(6) "TV-L E"
  [2]=>
  string(2) "9b"
}
```


 

### ==> Bei welchem Job stimmt die Angabe des Entgelts nicht? Bitte um Titel oder ID
(Ich habe die Settings verwendet, die wir auf jobs.fau.de in wp-admin/options-general.php?page=rrze-jobs nutzen, konnte aber keinen Job finden, der nicht in TVLE ist.)

**Comment by xwolfde** [comment]
In der Stellenanzeige [https://www.jobs.fau.de/jobs/akademische-raetin-akademischer-rat-auf-zeit-m-w-d-bes-gr-a-13-in-vollzeitbeschaeftigung-100-befristet-auf-3-jahre-mit-moeglichkeit-der-verlaengerung-um-weitere-3-jahre-90244132/ ](https://www.jobs.fau.de/jobs/akademische-raetin-akademischer-rat-auf-zeit-m-w-d-bes-gr-a-13-in-vollzeitbeschaeftigung-100-befristet-auf-3-jahre-mit-moeglichkeit-der-verlaengerung-um-weitere-3-jahre-90244132/), UnivIS ID 90244132 wird nicht die Besoldung A 13


UniviS-JSON:
http://univis.uni-erlangen.de/prg?search=positions&group=wiss&ignore=Person&show=json

Eintrag daraus:
```
{
   "orgname" : "Lehrstuhl für Neuere deutsche Literatur mit komparatistischem Schwerpunkt",
         "type2" : "voll",
         "desc1" : "- Wissenschaftliche Weiterqualifikation mit dem Ziel der Habilitation\r\n- Durchführung von Lehrveranstaltungen am Department Germanistik und Komparatistik im Umfang von 5 SWS im Bachelor-Bereich in den Basis-, Aufbau- und Vertiefungsmodulen an den FAU-Standorten in Erlangen und Nürnberg\r\n- Mitwirkung an den Forschungsvorhaben des Lehrstuhls in den Bereichen der deutschsprachigen (ggf. auch westeuropäischen und angloamerikanischen) Literatur vom 18. Jahrhundert bis zur Gegenwart, der interkulturellen Literaturwissenschaft und der Interart Studies\r\n- Übernahme von Aufgaben in der Studienorganisation und der akademischen Selbstverwaltung\r\n\r\n",
         "orgunit_en" : [
            "Faculty of Humanities, Social Sciences, and Theology",
            "Department of German Language and Literature",
            "Chair of Modern German and Comparative Literature (Prof. Dr. Bergmann)"
         ],
         "acontact" : "Person.phil/dgeko/LNDLI/berman",
         "start" : "01.04.2024",
         "creation" : "2023-08-21",
         "id" : "90244132",
         "type1" : "bef",
         "desc3" : "- Erfahrung in der interdisziplinären und internationalen Zusammenarbeit\r\n- Erfahrung im Verfassen von bzw. in der Mitarbeit an Drittmittelanträgen\r\n- Erfahrung in der Organisation wissenschaftlicher Veranstaltungen\r\n- Erfahrung in der Redaktion, Veröffentlichung und Herausgabe wissenschaftlicher Publikationen\r\n\r\n",
         "befristet" : "befristet auf 3 Jahre (mit Möglichkeit der Verlängerung um weitere 3 Jahre)",
         "desc2" : "- Überdurchschnittlich abgeschlossenes wissenschaftliches Hochschulstudium (Staatsexamen, M.A. oder äquivalent) sowie eine überdurchschnittlich abgeschlossene Promotion im Fach Germanistik oder Komparatistik (oder ggf. in einem anderen Fach mit einschlägiger literaturwissenschaftlicher Orientierung)\r\n- Bereitschaft und Befähigung zu engagierter und exzellenter Lehre \r\n- Organisationsfähigkeit, Teamfähigkeit und soziale Kompetenz\r\n- Hervorragende Deutsch- und Englischkenntnisse\r\n",
         "desc6" : "Prof. Dr. Franziska Bergmann\r\n\r\nDepartment Germanistik und Komparatistik\r\n\r\nLehrstuhl für Neuere deutsche Literatur mit komparatistischem Schwerpunkt\r\n\r\nBismarckstr. 1, \r\n91054 Erlangen\r\n\r\nE-Mail Sekretariat:\r\nndlg-sekretariat@fau.de",
         "vonbesold" : "A 13",
         "title" : "Akademische Rätin/Akademischer Rat auf Zeit (m/w/d), Bes.Gr. A 13, in Vollzeitbeschäftigung (100%) befristet auf 3 Jahre (mit Möglichkeit der Verlängerung um weitere 3 Jahre)",
         "group" : "wiss",
         "type4" : "nachv",
         "key" : "Position.phil/dgeko/LNDLI/akadem",
         "orgname_en" : "Chair of Modern German and Comparative Literature (Prof. Dr. Bergmann)",
         "lang" : "de",
         "orgunit" : [
            "Philosophische Fakultät und Fachbereich Theologie (Phil)",
            "Department Germanistik und Komparatistik",
            "Lehrstuhl für Neuere deutsche Literatur mit komparatistischem Schwerpunkt"
         ],
         "desc4" : "Die Stelle dient der wissenschaftlichen Qualifikation (Habilitation) im Bereich der Neueren deutschen Literatur mit komparatistischer Ausrichtung mit Bezug zu den oben genannten Forschungsschwerpunkten der Professur. Die Friedrich-Alexander-Universität fördert die berufliche Gleichstellung von Frauen. Frauen werden deshalb ausdrücklich aufgefordert, sich zu bewerben. Die Stelle ist für die Besetzung mit schwerbehinderten Menschen geeignet. Schwerbehinderte im Sinne des Schwerbehindertengesetzes werden bei gleicher fachlicher Qualifikation und persönlicher Eignung bevorzugt berücksichtigt. Die FAU erwartet eine hohe Präsenz an der Universität zur intensiven Betreuung der Studierenden.\r\n\r\n\r\nBitte senden Sie Ihre Bewerbung mit den üblichen Unterlagen (Motivationsschreiben, tabellarischer Lebenslauf inkl. eines Publikations- und Lehrveranstaltungsverzeichnisses, Zeugnisse, Nennung einer Referenz, zwei bis drei Seiten Exposé zum Habilitationsprojekt, Textprobe aus der Dissertationsschrift sowie ggf. zwei bereits veröffentlichte wissenschaftliche Aufsätze) ausschließlich in digitaler Form (in einer einzigen PDF-Datei) an das Sekretariat von Prof. Dr. Franziska Bergmann, ndlg-sekretariat@fau.de. Die Bewerbungsfrist endet am 31.10.2023.",
         "desc5" : "Die 1743 gegründete Friedrich-Alexander-Universität Erlangen-Nürnberg stellt sich im Bewusstsein ihrer starken Tradition einer verantwortungsvollen Gestaltung der Zukunft. Unter dem Motto Wissen bewegen vernetzt sie vor dem Hintergrund einer vielfältigen Hochschulkultur und eines hoch differenzierten Fächerspektrums wissenschaftliche Disziplinen mit Blick auf innovative Forschung und Lehre.\r\nAn der Friedrich-Alexander-Universität Erlangen-Nürnberg ist am Lehrstuhl für Neuere deutsche Literatur mit komparatistischem Schwerpunkt (Prof. Dr. Franziska Bergmann) voraussichtlich zum 01.04.2024 die Stelle eines/einer Akademischen Rätin/Akademischen Rates auf Zeit (m/w/d), Bes.Gr. A 13, in Vollzeitbeschäftigung (100%) befristet auf 3 Jahre (mit Möglichkeit der Verlängerung um weitere 3 Jahre) zu besetzen.\r\n",
         "enddate" : "2023-10-31"
      },
```

**Comment by thenickless** [comment]
Danke für die Infos.

### => gefixt

Die regex hat nicht gestimmt:

`preg_match('/^([a-z\-\s]*)\s*([0-9ab]+)$/i', $entgeld, $output_array)`

In der ersten Gruppe `([a-z\-\s]*)` wird auch das Whitespace mitgenommen durch `\s `


Ergebnis:

$output_array ist
```
array(3) {
  [0]=>
  string(4) "A 13"
  [1]=>
  string(2) "A "
  [2]=>
  string(2) "13"
}
```


Dadurch wird die Bedingung nie erfüllt

`if ($output_array[1] == "A") {`



Lsg:

`preg_match('/^([a-z\-]*)\s*([0-9ab]+)$/i', $entgeld, $output_array)`

**Comment by xwolfde** [comment]
Danke.

Vielleicht sollten wir das zum Anlass nehmen und nochmal genauer auch andere Fälle betrachten.

Fälle:

- (Usereingabe) => (Sanitizte Form)
- "TV L 9b"   => "TV-L E 9b"
- "Tarifvertrag E12"  => "TV-L E 12"
- "A12" => "Bes.Gr. A 12"
- "E-12" => "TV-L E 12"
- "TVLE 12"=> "TV-L E 12"
- "TVA-L BBiG" => "TVA-L BBiG"  (= Eigene Bezeichnung bei Azubis ohne Zahl)
- "TVA-L" => "TVA-L BBiG"  
- "C1" (Professur, kein TVL) =>  "Bes.Gr. C 1"
- "W2"  (Professur, kein TVL) => "Bes.Gr. W 2"

**Comment by thenickless** [comment]
### TL;DR : ist gefixt

Tja, das war nicht die hübsche Lsg, wie ich gerade wg https://github.com/RRZE-Webteam/rrze-jobs/issues/60 feststelle.


Denn mit 

`^([a-z\-\s]*)\s*([0-9ab]+)$`

wird 

`TV-L E9b`

richtig zerlegt in 

```
array(3) {
  [0]=>
  string(4) "TV-L E9b"
  [1]=>
  string(2) "TV-L E"
  [2]=>
  string(2) "9b"
}

```

Ohne `\s` natürlich nicht.


Darum wird jetzt einfach getrimmt


`$output_array[1] = trim($output_array[1]);`


damit die Bedingung 

`if ($output_array[1] == "A") {`

erfüllt werden kann.

**Comment by thenickless** [comment]
> Danke.
> 
> Vielleicht sollten wir das zum Anlass nehmen und nochmal genauer auch andere Fälle betrachten.
> 
> Fälle:
> 
>     * (Usereingabe) => (Sanitizte Form)
> 
>     * "TV L 9b"   => "TV-L E 9b"
> 
>     * "Tarifvertrag E12"  => "TV-L E 12"
> 
>     * "A12" => "Bes.Gr. A 12"
> 
>     * "E-12" => "TV-L E 12"
> 
>     * "TVLE 12"=> "TV-L E 12"
> 
>     * "TVA-L BBiG" => "TVA-L BBiG"  (= Eigene Bezeichnung bei Azubis ohne Zahl)
> 
>     * "TVA-L" => "TVA-L BBiG"
> 
>     * "C1" (Professur, kein TVL) =>  "Bes.Gr. C 1"
> 
>     * "W2"  (Professur, kein TVL) => "Bes.Gr. W 2"

Jepp. Ich werde nochmal "alle" Fälle durchgehen, also alle, die wir uns im Augenblick vorstellen können. Kann man das eigentlich "reverse EDV" nennen? Eingabe wird nicht geprüft, Ausgabe muss passen. ;-)

**Comment by thenickless** [comment]
@xwolfde 

willst du beim Entgelt der Besoldungsordnungen B, C, W

a) dass die Ausgabe beibehalten wird, wie sie derzeit online ist? => "A 12 BayBesO"
b) wie in deinem heutigen Bsp haben? => "Bes.Gr. A 12"
c) so dargestellt haben, wie sie ein paar (aber nicht alle) offizielle Websites zum Bayerischen Recht bzw Finanzen zeigenn? => "A 12 (BayBesG)"

(Bieten wir das Plugin auch anderen Bundesländern an und ist darum "Bes.Gr." einzig sinnvoll?)

(Die Anforderung, dass auch "umgedreht" geschrieben werden kann, wird klarerweise ebenso erfüllt. Siehe https://github.com/RRZE-Webteam/rrze-jobs/issues/60 )

**Comment by xwolfde** [comment]
Uff..

Ehrlich gesagt hab ich dazu keine feste Meinung. Egal wie wir es machen, es wird eh jemand um die Ecke kommen und es anders haben wollen.

C) klingt aber am besten.

Für andere User des Plugins wäre es gut wenn der Begriff BayBesO dann aber irgendwo eine constant wäre.
